config/routes.rb
Rails.application.routes.draw do
 root "sats#index"
 get "/sats/index", to: "sats#index"
 resources :sats
 
 get "/sats/estado/cerrados", to: "sats#cerrados"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sat.rb
class Sat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sats_controller.rb
class SatsController < ApplicationController
  def index
    @sats = Sat.all
  end
  
  def new
    @sats = Sat.new
  end
  
  def create
        @sat = Sat.new(sat_params)
        if  @sat.save
            flash[:notice] = "Tarea agregada correctamente"
            redirect_to sat_path(@sat)
        else
            render 'new'
        end 
  end
  
  def show
        redirect_to sats_path
  end
  
  
  def edit
       @sats = Sat.find(params[:id])
  end
  
  
  def update
       @sats = Sat.find(params[:id])
       if @sats.update(sat_params)
           flash[:notice]= "Tarea actualizada correctamente"
           redirect_to sats_path(@sat)
       else
           render 'edit'
       end
  end
  
  def cerrados
     @sats = Sat.all
     
  end
  private
        
        def set_sat
        @sats = Sat.find(params[:id])
        end
    
        def sat_params
            params.require(:sat).permit(:referencia, :descripcion, :estado)
        end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sats_helper.rb
module SatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
    <footer class="foo">jeangrau@outlook.es <%= image_tag "logo.png", :alt => "MediaMarkt", :title => "MediaMarkt", class: "imglogo"%></footer>
  </body>
</html>

app/views/sats/_formulario.html.erb
<% if @sats.errors.any? %>
    <h3>Se encontraron los siguientes errores</h3>
    <ul "list-group">
        <% @sats.errors.full_messages.each do |msg| %>
        <li class="list-group-item list-group-item-danger"> <%=  msg %>  </li>      
        
        <% end%>

    </ul>
<% end %>
<%= form_for @sats do |f|  %>
    
    <div class="col-md-3" style="float: left;">
    <p>
        <h2 style="font-weight: bold;">  Referencia </h2> 
         <%= f.text_field :referencia, class: "form-control" %>
        
    </p>
    </div>
    <div  class="form-group col-md-3" style="float: left;">
        <h2 style="font-weight: bold;">  Estado </h2> 
        <%= f.select(:estado, [['Abierto', 1], ['Tramitado', 2], ['Reclamo', 3], ['Cerrado', 4]], {}, { :class => 'form-control' }) %>
    </div>
    <div class="col-md-12" style="float: left;">
    <p>
        <h2 style="font-weight: bold;">  Descripción </h2> 
        <%= f.text_area :descripcion, :rows => 10, class: "form-control largos" %>
    </p>
    </div>
<div style="clear: both;"></div>

<div class="col-md-11"></div>
<%= f.submit "Enviar", class: " btn btn-success btn-md", height: "100px" %>
<% end %>
</div>
<div style="clear: both;"></div>
<div style="width: 100%; text_align:center;" class="col-md-12">
<h3>[<%= link_to "Ir al inicio", sats_path(@sats), class:"boton" %>]</h3>
</div>

app/views/sats/cerrados.html.erb
<h1>Gestión de SATs</h1>

<table class="table table-hover">
<tr>
    <th style="font-size: 20px">Referencia</th>
    <th style="font-size: 20px">Descripción</th>
    <th style="font-size: 20px" >Ver / Editar</th>
    
    <th style="font-size: 20px" >Estado</th>
</tr>
    <% @sats.each do |sat| %>
    <% if sat.estado == 4 %>
    <tr id ="rr">
        <td style="font-weight: bold; color: red" ><%= sat.referencia.first(12) %></td>
        <td ><%= sat.descripcion.first(90) %></td>
        <td ><%= link_to "[Editar/Ver]", edit_sat_path(sat), class: "xxx" %></td>
        
        <td>
          
               Cerrado
           
         </td>
         </td>
         </td>
 
    </tr>
    <% end %>
    
    
    <% end %>
    
</table>

<p>
    <%= link_to "Regresar", sats_path(@sats), class:"boton" %>
</p>

app/views/sats/edit.html.erb
<h1>Editar SAT</h1>
<%= render "formulario" %>

app/views/sats/index.html.erb
<h1>Gestión de SATs</h1>

<table class="table table-hover">
<tr>
    <th style="font-size: 20px">Referencia</th>
    <th style="font-size: 20px">Descripción</th>
    <th style="font-size: 20px" >Ver / Editar</th>
    
    <th style="font-size: 20px" >Estado</th>
</tr>
    <% @sats.each do |sat| %>
    <% if sat.estado < 4 %>
    <tr id ="rr">
        <td style="font-weight: bold; color: red" ><%= sat.referencia.first(12) %></td>
        <td ><%= sat.descripcion.first(90) %></td>
        <td ><%= link_to "[Editar/Ver]", edit_sat_path(sat), class: "enlace" %></td>
        
        <td>
            <% if sat.estado == 1%>
             <%= "Abierto"%>
            <%end%>
            <% if sat.estado == 2%>
             <%=  "Tramitado" %>
            <%end%>
             <% if sat.estado == 3%>
             <%=  "Reclamo" %>
            <%end%>
            
         </td>
         </td>
         </td>
 
    </tr>
    <% end %>
    
    
    <% end %>
    
</table>

<p>
    <%= link_to "Nuevo SAT", new_sat_path, class:"enlace" %>
</p>

app/views/sats/new.html.erb
<h1>Nuevo SAT</h1>
<%= render "formulario" %>